backend:
  name: git-gateway
  repo: marawan46/astro-tr
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"


i18n:
  structure: multiple_folders
  locales: [en, ar]
  default_locale: en

collections:
  - name: "services"
    label: "Services"
    folder: "src/content/services"
    create: false
    i18n: true
    extension: "json"
    fields:
      - { label: "Section Title", name: "title", widget: "string", i18n: true }
      - label: "Services List"
        name: "items"
        widget: "list"
        i18n: true
        fields:
          - { label: "Service Title", name: "title", widget: "string", i18n: true }
          - { label: "Description", name: "description", widget: "text", i18n: true }
